Update Vercel Deployment yml file

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -1,4 +1,4 @@
-name: Template Docs Production Deployment
+name: Template.Docs Production Deployment
 env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
@@ -7,23 +7,23 @@ on:
     branches:
       - main
 jobs:
-  Deploy-Preview:
+  Deploy-Production:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Install Vercel CLI
         run: npm install --global vercel@latest
       - name: Pull Vercel Environment Information
-        run: vercel pull --yes --environment=preview --token=${{ secrets.AWESOME_TOOLS_TOKEN }}
+        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
       - name: Build Project Artifacts
-        run: vercel build --token=${{ secrets.AWESOME_TOOLS_TOKEN }}
+        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
       - name: Deploy Project Artifacts to Vercel
-        run: |
-          deployment_output=$(vercel deploy --prebuilt --token=${{ secrets.AWESOME_TOOLS_TOKEN }} 2>&1)
-          deployment_url=$(echo "$deployment_output" | grep -oP '(?<=Preview: )\S+')
-          if [[ $? -eq 0 ]]; then
-            echo "Deployment URL: $deployment_url"
-          else
-            echo "Error deploying: $deployment_output"
-            exit 1
-          fi
+      run: |
+            deployment_output=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
+            deployment_url=$(echo "$deployment_output" | grep -oP '(?<=Preview: )\S+')
+            if [[ $? -eq 0 ]]; then
+                echo "Deployment URL: $deployment_url"
+            else
+                echo "Error deploying: $deployment_output"
+                exit 1
+            fi
