Remove `pnpm-lock` file; Update Prod yml file

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -18,12 +18,12 @@ jobs:
       - name: Build Project Artifacts
         run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
       - name: Deploy Project Artifacts to Vercel
-      run: |
-            deployment_output=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
-            deployment_url=$(echo "$deployment_output" | grep -oP '(?<=Preview: )\S+')
-            if [[ $? -eq 0 ]]; then
-                echo "Deployment URL: $deployment_url"
-            else
-                echo "Error deploying: $deployment_output"
-                exit 1
-            fi
+        run: |
+          deployment_output=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
+          deployment_url=$(echo "$deployment_output" | grep -oP '(?<=Preview: )\S+')
+          if [[ $? -eq 0 ]]; then
+            echo "Deployment URL: $deployment_url"
+          else
+            echo "Error deploying: $deployment_output"
+            exit 1
+          fi
